# Model arguments
model_name_or_path: /mnt/data-rundong/mistral-7B-v0.1
model_revision: main
torch_dtype: float16
use_flash_attention_2: false
disable_auto_config: true
model_type: mistral
va_ncodes: 16384
va_embedding_dim: 1024
va_checkpoint: /mnt/data-rundong/RobotVQ/1210-lr1e-6-8node-8v100-bs4-seqlen3-attn12-7actdec4-drop01-crop-kla-dim1024-imagenetnorm-imagegan-ganfeatloss02/checkpoints/step_checkpoint-step_30000.ckpt

# Data training arguments
preprocessing_num_workers: 12
# data_root: /mnt/data-rundong/robot_datasets/0531-action111-bridge-noMask-woResidual_tokenized_stacked/
data_roots:
  - /mnt/data-rundong/robot_datasets/1210-lr1e-6-8node-8v100-bs4-seqlen3-attn12-7actdec4-drop01-crop-kla-dim1024-imagenetnorm-imagegan-ganfeatloss02_step30000_tokenized_stacked_split/pizza_width/

padding_side: right
num_visual_action_tokens: 16384
static_video_description:
  - ""
dataset_type: dataset # or iterable_dataset
action_before_vision: false
wo_vision: true
wo_text: true

# SFT trainer config
deepspeed: configs/deepspeed/ds_zero3.json
bf16: false
fp16: true
do_eval: true
eval_strategy: steps
eval_steps: 1000
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
log_level: info
logging_strategy: steps
logging_steps: 5  
lr_scheduler_type: cosine
max_seq_length: 1024
max_steps: 50000
output_dir: /mnt/data-rundong/Adapter/1226-qilin/LoRA-rank128/
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 4
remove_unused_columns: true
report_to:
- tensorboard
save_strategy: steps
save_steps: 2000
save_total_limit: 40
load_best_model_at_end: true
seed: 42
warmup_ratio: 0.01
save_on_each_node: false